// ── Just Curious Virtual Office — Webview Entry Point ────────────

// Shared constants (single source of truth for colors, labels, etc.)
export {
  BUBBLE_EMOJIS,
  DEPT_COLORS,
  DEPT_LABELS,
  DEPT_NEON,
  DEPT_POPUP_COLORS,
  IDLE_TIMEOUT_MS,
  PERMANENT_ROLES,
  SPEECH_BUBBLE_COLORS,
  STATE_COLORS,
  STATE_LABELS,
  TASK_STATUS_COLORS,
} from './jc-constants.js';
export { renderJCBubble, renderJCOverlay } from './jc-overlay.js';
export type { DashboardMember } from './jc-state.js';
export {
  jcActivitySummaryUpdate,
  jcAddSpeechBubble,
  jcGetActivitySummary,
  jcGetAllTasks,
  jcGetDashboardMembers,
  jcGetDeptColor,
  jcGetIdleMembers,
  jcGetMemberNames,
  jcGetSpeechBubbles,
  jcGetStateColor,
  jcIsPermanentResident,
  jcRecordActivity,
} from './jc-state.js';
export {
  JC_ENTRANCE,
  jcAbsenceBulkSync,
  jcAbsenceUpdate,
  jcGetAbsenceInfo,
  jcGetAbsentMemberAtDesk,
  jcGetBreakTarget,
  jcGetDeptStats,
  jcGetDeskPosition,
  jcGetDeskTaskStatus,
  jcGetMemberAtDesk,
  jcGetMemberForAgent,
  jcGetMemberInfo,
  jcGetMemberRuntime,
  jcGetMemberTaskStatus,
  jcGetPokerSeat,
  jcGetPresentMemberIds,
  jcIsActive,
  jcLoadConfig,
  jcMemberArriving,
  jcMemberDeparted,
  jcMemberLeaving,
  jcMemberStateChange,
  jcTasksBulkSync,
  jcTaskUpdate,
  jcTriggerLiaison,
  jcTriggerSubagentThinking,
  jcTriggerTaskCompleted,
  jcTriggerWave,
  jcUpdateMappings,
  POKER_TABLE_SEATS,
} from './jc-state.js';
export type {
  AbsenceInfo,
  JCBubbleType,
  JCConfigData,
  JCMemberRuntime,
  JCState,
  NameplateInfo,
  SpeechBubble,
  TaskDefinition,
  TaskStatus,
} from './jc-types.js';
